### ISSUE TITLE
Projection Matrix

### ISSUE THREAD

**Issue by ted537** [skycoin/cx-game#120]
Previously, I had passed the projection matrix through to a shader as a uniform each time we draw something. @Planutim undid this change. We need to update the projection matrix each frame. Should we apply this to each shader program at the start of each frame?

**Comment by Planutim** [comment]
i had to separate the projection matrix, because the zooming is tied to projection.

**Comment by Planutim** [comment]
Also you mentioned in the code comments that you'd eventually move it out of drawquad function, because it should not set up projection matrix

**Comment by Planutim** [comment]
Shouldn't we have unified projection matrix on all shader programs? We just query updated projection matrix and set shader's uniform alongside other variables

**Comment by ted537** [comment]
We can assume that scheme, but it might be nice to have an alternate projection matrix for distant background objects with a parallax effect
