### ISSUE TITLE
Redraw when windows resize

### ISSUE THREAD

**Issue by herux** [skycoin/cx-game#203]

**Comment by ted537** [comment]
This appears to be working

**Comment by herux** [comment]
I mean windows resize like below video, please check
https://user-images.githubusercontent.com/4566493/124560142-b040cf80-de66-11eb-8a2f-05da4f77568b.mov

**Comment by ted537** [comment]
I'm not experiencing this issue on linux on the latest `main`. Perhaps this is an OS X specific issue or that video is from an earlier version
