### ISSUE TITLE
create VBOElement for each draw type

### ISSUE THREAD

**Issue by Planutim** [skycoin/cx-game#222]
for each draw type, we should have

- VBOelement struct

have one file
- for setup of glsl shader
- for uniforms, etc
- for "prep VBO stage"
- for draw stage

**Comment by Planutim** [comment]
so we do two iterations

1> First iteration
- go through all objects for each list; items, middle layer/furniture, agents, etc and do fulstrum text
- for each object passing fulstrum test, we sort them by draw type 
- then we construct a VBO object for that draw type and object type and we upload it at the end

Lets call that "PrepVBO step"
- culling
- preperation of VBO object
- uploading VBO

2> Then in draw step
- we setup opengl context
- we send VBO id
- we tear down vbo context

**Comment by ted537** [comment]
Would it be correct to say that the draw step occurs many more times than the preparation step?

**Comment by Planutim** [comment]
can't say for sure, probably just as much as drawing of parameters wont change

**Comment by ted537** [comment]
> can't say for sure, probably just as much as drawing of parameters wont change

We only need to reconstruct VBO if something like vertex attributes change. Uniforms (such as fading color tint) can be altered separately.

**Comment by ted537** [comment]
Some draw type's simply need a quad, so they don't necessarily need their own VBO
