### ISSUE TITLE
create particle type

### ISSUE THREAD

**Issue by Planutim** [skycoin/cx-game#224]
- a particle that bounces but is solid

- a particle that does not bounce but is alpha blended and not solid

- a particle that floats and is alpha blended (drifts in air, no gravity)

And  two draw modes

~~1> solid particle~~ 

~~2> alpha blended particle (has transparency, glowing, etc)~~

And three physics modes

~~1> bounces, gravity~~

~~2> Does not bounce, stops on impact, gravity~~

~~3> "drifts" at fixed velocity, no gravity~~

- when you fire gun do "shell casing" particle coming out of player
- when you hit block, do "debris" particle, etc
- test a spark or type of glowing/alpha blended particle
- create a struct called "Emitter" which is just something that creates particles, we can throw in game

**Comment by ted537** [comment]
Types could look something like this

```go

type DrawMode uint32
const (
    SolidDrawMode DrawMode = iota
    AlphaBlendedDrawMode
)

type PhysicsMode uint32
const (
    BouncePhysicsMode PhysicsMode = iota
    NoBouncePhysicsMode
    DriftPhysicsMode
)

type Particle struct {
  DrawMode DrawMode
  PhysicsMode PhysicsMode
}

type ParticleID uint32

type Emitter struct {
    ParticleID ParticleID
}

func (emitter *Emitter) Emit() {}
