### ISSUE TITLE
Collision to Left and Right is not working

### ISSUE THREAD

**Issue by herux** [skycoin/cx-game#282]
Collision to Left and Right is not working, always return false

**Comment by ted537** [comment]
What returns false? Horizontal collisions appear to be working for both the player and enemies

**Comment by herux** [comment]
I try debugging at leap.go file, like attached screenshot, it return always false. 
or am I doing something wrong ?
<img width="1194" alt="Screen Shot 2021-08-04 at 16 27 07" src="https://user-images.githubusercontent.com/4566493/128157939-683e7981-2452-49a0-8209-b54ec7fdf476.png">

**Comment by herux** [comment]
it happen also on Drilling.go file, when I debug more deeper
<img width="1238" alt="Screen Shot 2021-08-04 at 16 35 39" src="https://user-images.githubusercontent.com/4566493/128158605-9ab3c575-8919-45d2-8d65-9b8fa64d9042.png">

`func (body *ParticleBody) isCollidingLeft(planet worldcollider.WorldCollider, newpos cxmath.Vec2) bool {
	// don't bother checking if not moving left
	if body.Vel.X >= 0 {
		return false
	}
	bounds := body.bounds(newpos)
	bottom := int(round32(body.Pos.Y - body.Size.Y/2 + eps))
	top := int(round32(body.Pos.Y + body.Size.Y/2 - eps))
	for y := bottom; y <= top; y++ {
		if planet.TileIsSolid(int(bounds.left), y) {
			body.Collisions.Left = true
			return true
		}
	}
	return false
}`

method planet.TileIsSolid() that return false

**Comment by ted537** [comment]
Well in those screenshots, the slime doesn't appear to be hitting any tiles on the left or right so I would expect the method to return false.

**Comment by ted537** [comment]
The drilling behaviour seems to be unintended though. I'll look into it.
