### ISSUE TITLE
Create 3rd tool for pipe placement and wire placement, background tile placement

### ISSUE THREAD

**Issue by Planutim** [skycoin/cx-game#320]

**Comment by ted537** [comment]
When you say "3rd tool", is this the order you are referring to?

1. Foreground build tool
2. Enemy Tool
3. Background build tool

**Comment by Planutim** [comment]
no it is 
1. Furniture
2. Tile placement
3. Pipe and Wire placement

**Comment by ted537** [comment]
Is that indentation intentional? Are (3),(4),(5) children of (2) ?
