### ISSUE TITLE
enemies stuck in ground?

### ISSUE THREAD

**Issue by Planutim** [skycoin/cx-game#327]
![photo_2021-08-10_12-19-35](https://user-images.githubusercontent.com/5618012/128865594-5c94d09d-6d58-444c-8174-2350d0796f5f.jpg)

**Comment by Planutim** [comment]
its the screenshot synth provided me. I assume its because of regenerated planet

**Comment by ted537** [comment]
How was planet regenerated? Was the `newplanet` command used?

**Comment by Planutim** [comment]
bug is not reproducible,closing the issue
