### ISSUE TITLE
texture offset

### ISSUE THREAD

**Issue by Planutim** [skycoin/cx-game#342]
Have F4 to offset x/y by half a pixel.
- Which is 1/64f because even if pixel aligned it wont be in center of pixel. It would be on edge.
![photo_2021-08-11_15-18-13](https://user-images.githubusercontent.com/5618012/129056434-c73e67da-2db1-40f5-aa81-50d8dabba7af.jpg)
  See these weird vertical lines
it may be  because tx coordinate on texture is not in center of pixel but is on edge

Have f5 to change the TX texture coordinate so its in center of pixel and not on edge.
- And F5 to toggle bool.  If its 32x32 pixels then its 0.0f to etc

And 0.0f is actually at intersection of 4 pixels. Not in center of pixel for the texture.
if texture sheet is 16 elements then each texture is 1/16 f. For offset.
And then if its 32 pixels per square.
then center of pixel 0,0 maybe is offset by 1.0f /(16*32)
32 pixels per tile
16  tiles per sprite sheet.
Sprite sheet texture goes from 0.0f to 1.0

**Comment by ted537** [comment]
Are there any other tiles (platform possibly) on which this effect is more visible? I'm having trouble reproducing the issue.

**Comment by Planutim** [comment]
if you bump into a wall while moving the focus area with you


you will get these lines
