### ISSUE TITLE
pipesim merging

### ISSUE THREAD

**Issue by Planutim** [skycoin/cx-game#369]
The pipesim elements shouldn't merge with the objects. It should be placed on a layer between the objects and the walls. Also, it should only merge with elements of the same type (vent pipes with vent pipes, wires with wires, etc)

**Comment by ted537** [comment]
Does this mean we now have four layers of tiles?


- Wall
- Pipe
- Mid
- Top

**Comment by Planutim** [comment]
No. Mid layer is furniture/pipe
