### ISSUE TITLE
pipesim connection

### ISSUE THREAD

**Issue by Planutim** [skycoin/cx-game#370]
Select tile
Then have them press up/down/left/right
and if already connected will disconnect

**Comment by ted537** [comment]
In other words,

- User selects the pipe tool
- User clicks on an existing pipe tile in the world
- User presses arrow keys to toggle connections of the selected pipe tile with its neighbours

Is that correct?

**Comment by Planutim** [comment]
yes, or having to hold the mouse button while placing pipes to have them connected, and one mouse button is released, disconnect
