### ISSUE TITLE
SpriteLoader

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx-game#41]
you can look at the code

1. Take array of sprite sheets

2. Load the .png into memory as bitmap for the list

3. Time how long it takes

4. Try wrapping each sprite load in a goroutine because the read will block

5. Time difference between serial read/load and doing them in parrallel in a goroutine

6. Have "read png" function

And check if png is already loaded to bitmap with a map, cache. And put filename in map if the file is already loaded or scheduled to be loaded

7. Have an integer id for the .png

---

The bitmap is slice with 4 bytes per pixel. RGBA

And has width in pixels and height in pixels. As a struct

Struct Bitmap_RGBA {
 Width int
Height int
pixels []byte
}

And time 
- how long to read file from disc
- how long to convert the .png to internal format

When we have 800 or 2000 sprite sheets, it will get slow. So need that for later.

To speed up level loading and startup time.

We load and process the spritesheet in background while game is starting or player is on intro screen.

---

Create /stats folder
- put the sprite loading stats in /stats module
- put timing/profiling code in stats module (startup time, total sprite loading time, etc)

**Comment by ted537** [comment]
Should this component deal with uploading the bitmap to a texture on the GPU or is that out of scope?
