### ISSUE TITLE
Tile Palete Selector

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx-game#42]
1> Allow a box on screen, that can be used to select tiles
- example, 8x8 grid of tiles

2> Allow placement of tiles with map

3> All tiles should be loaded to internal tile sheet and have integer id
- also should have name string (internal)

4> Tiles should have parameter for x,y position in tile palette selector

5> Add a button for toggling free camera (like f2) and add a button for toggling tile palette (Debug mode; f3)
- have bool for free camera
- have bool for showing tile selector pallete

**Comment by ted537** [comment]
I take it that "internal sprite sheet" means that the tilemap compiles its own sprite sheet containing only the relevant tiles?
