### ISSUE TITLE
[Shader] Automatically generate black outlines

### ISSUE THREAD

**Issue by Luis-Tavares** [skycoin/cx-game#442]
The foreground tiles must have their outlines generated automatically by code. I'm currently using color #1b1b1b for outlines, but we can try other tones of black.
It's a little hard to notice the difference right now, but this is very important for some brighter areas.

![image](https://user-images.githubusercontent.com/83770527/132889967-fbc22630-b9de-48e0-863f-f66da386990f.png)

**Comment by ted537** [comment]
# Steps to Implement

For each layer:
- (1) Render all tiles to a texture (instead of directly to the viewport)
- (2) Run rendered tiles through an edge detection filter / kernel to get border

The result of (2) can be rendered directly to the viewport.

https://en.wikipedia.org/wiki/Edge_detection
