### ISSUE TITLE
shockwave shader

### ISSUE THREAD

**Issue by Planutim** [skycoin/cx-game#472]
https://www.youtube.com/watch?v=SCHdglr35pk

- shockwave shaders for explosion effects
- ring shock wave and lens shock wave
- also color distorted version, where gaussian blur and different colors moved different amounts

**Comment by Planutim** [comment]
radius of shockwave must be 8 blocks, and duration is 0.5 seconds, slowly fading out in thickness and speed

**Comment by ted537** [comment]
How is shockwave triggered?

**Comment by Planutim** [comment]
i bind it to "V" key

**Comment by ted537** [comment]
closing for now. appears to be working
