### ISSUE TITLE
Import Tiled maps into the game

### ISSUE THREAD

**Issue by Luis-Tavares** [skycoin/cx-game#480]
The maps of the game are being built on Tiled. Its files are on `kcg\luis\tiled` files
We need to import different Tiled maps into the game. On the first version, the player is going to select on the load screen which map he's going to play and it'll load an entire map of Tiled.
Later we maybe incorporate Tiled maps into some procedurally generated areas, but you don't need to worry about that right now.
Tiled is free, so I advise you to also download it, so you can check how the map should look like and how the layers are organized.

**Comment by ted537** [comment]
Looking through the [TMX](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/) file format, populating the layers should be a straightforward task. The trickier element will be mapping the `.tsx` resources to the in-game tiles.

**Comment by ted537** [comment]
`.png` spritesheets hold many sprites. `.tsx` files map sprites to spritesheets. Our custom sprite `.yaml` files also map sprites to spritesheets. Our custom tile `.yaml` files map tiles to sprites.

Perhaps we should replace our custom sprite `.yaml` files with the same `.tsx` files that we are already using within Tiled. Adopting a single source of truth will reduce the friction in adding/updating assets.

Additionally, Tiled supports custom [properties](https://doc.mapeditor.org/en/stable/manual/custom-properties/). We may be able to embed tile information within these properties to further consolidate the map information.

**Comment by ted537** [comment]
According to the Tiled [documentation](https://doc.mapeditor.org/en/stable/manual/layers/#tile-layers) on Tile layers, properties only exist on tiles - they cannot be defined on a specific instance of a tile. This is ideal for our purposes.

**Comment by ted537** [comment]
Perhaps each tile in a Tiled map could have a "cxgame" property which contains the name of the CX-game tile to insert.

**Comment by ted537** [comment]
Of the two [libraries](https://doc.mapeditor.org/en/stable/reference/support-for-tmx-maps/) listed by Tiled, [go-tiled](https://github.com/lafriks/go-tiled) appears to be more mature / fully featured.

**Comment by ted537** [comment]
Note that go-tiled does not currently [support](https://github.com/lafriks/go-tiled/issues/10) infinite maps.
