### ISSUE TITLE
Star Field

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx-game#5]
Create a folder "starfield"

And a folder cmd/starfield and a main.go in this folder.

In assets folder, create a folder "starfield"

- when cmd/starfield is run
- open an opengl window (see main.go in root folder)
- load .png file for starfield in the star field folder as a texture (texture loader)
- read a yaml file, that specifies for all files or for each files, the pixel x/y size for sprites on sheet. All sprites on sheet must have the same size and be square
- if there are multiple starfield files, load all of them and choose a random one
- draw stars randomly to screen
- use library "github.com/urfave/cli/v2" for command line input and parameters

Example Starfields:

![f20045c4d721c0ab7010a88fc6a2cc57](https://user-images.githubusercontent.com/54745307/112155841-aaf5a700-8c20-11eb-91f8-8e2b587a2725.jpg)

![b1dec4f7e6848c3ef296ff0e6db2209e (1)](https://user-images.githubusercontent.com/54745307/112155931-c1036780-8c20-11eb-8da0-583f938030c5.jpg)

Make a function for
- init star field
- draw starfield

- each star must be represented as a struct
- a star should have a "x,y" position and should have a "distance" or depth parameter (all floats)
- stars should also have a "size" parameter

- use library "github.com/urfave/cli/v2" for command line input
- have command line argument for resolution, ex. 800x600
- make  readme.md with command examples
- have command line argument for specifying the number of stars to draw on the screen

- add an OpenGl Shader
- load a 1 dimensional 1x128 pixel texture file (called a gradient)
- use the gradient and for each star, choose a random number from 0 to 1 and use that float to sample from the gradient file to get the color of the star
- if there are multiple "gradient" files in the directory, have program make a list and choose one randomly.

- add an option, when generating a star, for "hard-minimum-star-separation" in pixels, and if two stars are within the minimum distance of each other, then regenerate position of star

![download](https://user-images.githubusercontent.com/54745307/112149244-b98c9000-8c19-11eb-8f6b-0c5dd50dfe07.jpeg)

Find the formula for a 2d dimensional Gaussian. Choose parameters for the Gaussian such that the gaussian's 2d projection onto a 2 dimensional plane, makes a fuzzy elliptical shape with
- angle theta from horizontal
- center offset x
- center offset y
- length along the axis of the gaussian
- width of elliptical shape
- magnitude of the gaussian (constant factor) + multiplicative factor (k+a*x)

The formula in x,y is

![download](https://user-images.githubusercontent.com/54745307/112149291-c7421580-8c19-11eb-9ca3-5e4f2302c89f.png)

Use 2x2 matrix representation for the Gaussian. Its easier.
- you may need a 3x3 matrix later, so maybe use 3x3 and use narrow width (small value) in the depth axis
- 
When a star is generated, sample the gaussian and with probability 1 minus output of Gaussian "reject" the star and generate a new start. Aka sample the gaussian to generate the stars.
- have parameter for percentage of stars in the gaussian band
- and generate the other stars normally

---

Implement Parallax for the star field

Each star should have 
- an x position and a y position
- a "depth"

Then each star has a 
- draw position (x,y)
- stars with closer positions (lower depth), should move more in x as camera moves in X dimension
- use the parallax formula for the draw position

The star field should "wrap" along screen. But the star field area for warping should be larger than the screen area. And starfield size in x,y should be parameter set by command line.
- example screen is 400x800, but star field is 600x1200 (meaning every 600 pixels in x, the starfield warps around completely)

**Comment by ted537** [comment]
I see we have a starfield. @herux  Is this completed?
