### ISSUE TITLE
control station, radar and possibly others should have ground placement restriction

### ISSUE THREAD

**Issue by Planutim** [skycoin/cx-game#522]
![DeepinScreenshot_select-area_20211024174650](https://user-images.githubusercontent.com/5618012/138592709-b9be3968-6fe6-40f6-8cf5-1e1aee6f6a79.png)

**Comment by ted537** [comment]
Given that these furnitures are loaded from the Tiled map, it would make sense to define the ground placement restriction as a property on the Tileset tile.

![image](https://user-images.githubusercontent.com/8276517/143296912-84e72129-85f0-4299-8513-eb6262c60ee6.png)
