### ISSUE TITLE
Port Perlin Function from C to Golang

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx-game#9]
Convert the following code into golang 
- https://github.com/Gnomescroll/Gnomescroll/blob/master/src/c_lib/t_gen/perlin_extra.hpp

---

- create a folder "procgen"
- put the golang file in procgen/perlin.go 

----

- use the following library to replace "Twister"
-  https://pkg.go.dev/github.com/seehuhn/mt19937

**Comment by d29107d** [comment]
i see the code,this task had finished,can you close the issue?
